name: php-cs-fixer
on: [pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
        working-directory: ./src
      - name: Dry-run php-cs-fixer
        run: |
          ./vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no . || true
        working-directory: ./src
      - name: Execute php-cs-fixer
        run: |
          ./vendor/bin/php-cs-fixer fix --using-cache=no
        working-directory: ./src
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: pxp-cs-fixer by Github Actions
      - name: Run if changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
      - name: Run if no changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"